version: '3.7'

services:

  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=testDB
    ports:
      - '5432:5432'
    volumes:
    - /C/ProgramData/DockerDesktop/vm-data:/var/lib/postgersql
